# Github action name
name: Deploy CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]
    # Don't trigger the workflow for README file changes.
    paths-ignore: [ README.md ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single job named 'deploy'
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Deploy task
      - name: Deploy to heroku
        uses: Dhina17/heroku-deploy@master
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          # Email that you use with heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          # The appname to use for deploying/updating
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          # Set the stack to container
          stack: "container"
        env:
          HD_MONGODB_CONNECTION_STRING: ${{secrets.MONGODB_CONNECTION_STRING}}
          HD_BUSINESS_NEWS_API_KEY: ${{secrets.BUSINESS_NEWS_API_KEY}}
          HD_ENTERTAINMENT_NEWS_API_KEY: ${{secrets.ENTERTAINMENT_NEWS_API_KEY}}
          HD_GENERAL_NEWS_API_KEY: ${{secrets.GENERAL_NEWS_API_KEY}}
          HD_HEALTH_NEWS_API_KEY: ${{secrets.HEALTH_NEWS_API_KEY}}
          HD_SCIENCE_NEWS_API_KEY: ${{secrets.SCIENCE_NEWS_API_KEY}}
          HD_SPORTS_NEWS_API_KEY: ${{secrets.SPORTS_NEWS_API_KEY}}
          HD_TECHNOLOGY_NEWS_API_KEY: ${{secrets.TECHNOLOGY_NEWS_API_KEY}}